### ISSUE TITLE
Tasks

### ISSUE THREAD

**Issue by WorksOfLiam** [NielsLiisberg/noxDB#1]
* [x] 1: Update repo with the latest source code
* [x] 2: Move project to new file structure: `src`, `headers`, `tests`
* [x] 3: Create makefile to build entire project (see [this](https://github.com/NielsLiisberg/Node.RPG/blob/master/makefile) for an example)
* [x] 4: Re-write makefile to support the new file structure
* [x] 4: Convert all fixed RPGLE to free-format
* [x] 5: Automate all the unit tests

**Comment by NielsLiisberg** [comment]
Great work 👍
